steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/fuse-service', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/fuse-service']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'fuse-service'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/fuse-service'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'REDIS_HOST=10.8.239.3,PROJECT_ID=${PROJECT_ID},LOCATION=us-central1'
      - '--project'
      - '${PROJECT_ID}'
      - '--quiet'

images:
  - 'gcr.io/${PROJECT_ID}/fuse-service'
